import type { MapContract } from "./schema.ts";

// The shareable artifact: a clean, pastable Markdown summary of a corpus — what it's about, the axes
// it varies along, what to read next, and the frontier just outside it. Not the 3.5MB explorer; the
// insight, in a form you can drop in a post. Reads only the MapContract a run already produces.

const fmtDate = (t?: number) => (t ? new Date(t).toISOString().slice(0, 10) : "");

export function buildReport(D: MapContract, name = "Corpus"): string {
  const n = D.ids.length;
  const dates = (D.dates || []).filter((d): d is number => !!d).sort((a, b) => a - b);
  const span = dates.length ? `${fmtDate(dates[0])} → ${fmtDate(dates[dates.length - 1])}` : "";
  const hub = D.hub || D.ids.map(() => 0);
  const link = (i: number) => (D.urls?.[i] ? `[${D.titles[i]}](${D.urls[i]})` : D.titles[i]);
  const regionOf = (i: number) => D.clusters.find((c) => c.c === D.cluster[i])?.label || "";
  const out: string[] = [];
  const solid = D.axes.filter((a) => !a.weak);
  const noisy = D.axes.filter((a) => a.weak);

  out.push(`# ${name} — eidoscope report\n`);
  out.push(`**${n} documents**${span ? ` · ${span}` : ""} · ${D.k} regions · ${solid.length} main axes${noisy.length ? ` (+${noisy.length} minor)` : ""}\n`);

  // What it's about — regions by size, each with its most-central (highest-hub) member
  out.push(`## What it's about\n`);
  const bySize = D.clusters.slice().sort((a, b) => b.n - a.n);
  for (const c of bySize) {
    const members = D.ids.map((_, i) => i).filter((i) => D.cluster[i] === c.c);
    const top = members.sort((a, b) => (hub[b] || 0) - (hub[a] || 0))[0];
    out.push(`- **${c.label}** (${c.n})${top != null ? ` — e.g. *${D.titles[top]}*` : ""}`);
  }

  // How it varies — LEAD with the main axes and show the % of variation each explains; the minor
  // (<2%) ones get quarantined below with their % too, not listed as equals. Show the number, not a verdict.
  const pct = (a: typeof D.axes[number]) => (a.variance != null ? ` — _${(a.variance * 100).toFixed(1)}% of the variation_` : "");
  out.push(`\n## How it varies\n`);
  out.push(solid.length
    ? `The dimensions your reading actually varies along, biggest first — each shows how much of the variation it explains:\n`
    : `⚠ Every discovered axis explains under 2% of the variation — read the map's axes with caution.\n`);
  for (const a of solid) out.push(`- **${a.name}** — ${a.low} ↔ ${a.high}${pct(a)}`);
  if (noisy.length) {
    out.push(`\n**${noisy.length} minor axes** each explain under 2% of the variation — real but thin, don't over-read them:\n`);
    for (const a of noisy) out.push(`- ~~${a.name}~~ — ${a.low} ↔ ${a.high}${pct(a)}`);
  }

  // Read next — highest-influence documents, filtered to unread when read-state is known
  const known = (D.read || []).some((r) => r !== undefined);
  const readN = (D.read || []).filter((r) => r === true).length;
  out.push(`\n## Read next\n`);
  out.push(known
    ? `You've opened **${readN} of ${n}** (${Math.round((100 * readN) / n)}%). The most influential of the **${n - readN}** you haven't:\n`
    : `The most connected documents (structural influence):\n`);
  const pool = D.ids.map((_, i) => i).filter((i) => !known || D.read?.[i] !== true);
  pool.sort((a, b) => (hub[b] || 0) - (hub[a] || 0)).slice(0, 10).forEach((i, r) => out.push(`${r + 1}. ${link(i)} — *${regionOf(i)}*`));

  // Frontier — the canon you cite but don't own
  if (D.ghosts && D.ghosts.length) {
    out.push(`\n## Your frontier — ${D.ghosts.length} papers you cite but don't own\nThe foundations just outside your library, by how many of your documents cite each:\n`);
    D.ghosts.slice().sort((a, b) => b.n - a.n).slice(0, 12).forEach((g, r) =>
      out.push(`${r + 1}. [${g.title}](${g.url}) — cited by **${g.n}** of your docs`));
  }

  out.push(`\n---\n_Generated by [eidoscope](https://github.com/deepfates/eidoscope). Open the \`.html\` for the interactive map, or the \`.eido\` in the viewer._`);
  return out.join("\n") + "\n";
}
