import type { MapData } from "./render.ts";
import { scoreRedundancy } from "./redundancy.ts";

// The shareable artifact: a clean, pastable Markdown summary of a corpus — what it's about, the axes
// it varies along, what to read next, and the frontier just outside it. Not the 3.5MB explorer; the
// insight, in a form you can drop in a post. Reads only the MapData a run already produces.

const fmtDate = (t?: number) => (t ? new Date(t).toISOString().slice(0, 10) : "");

export function buildReport(D: MapData, name = "Corpus"): string {
  const n = D.ids.length;
  const dates = (D.dates || []).filter((d): d is number => !!d).sort((a, b) => a - b);
  const span = dates.length ? `${fmtDate(dates[0])} → ${fmtDate(dates[dates.length - 1])}` : "";
  const hub = D.hub || D.ids.map(() => 0);
  const link = (i: number) => (D.urls?.[i] ? `[${D.titles[i]}](${D.urls[i]})` : D.titles[i]);
  const regionOf = (i: number) => D.clusters.find((c) => c.c === D.cluster[i])?.label || "";
  const out: string[] = [];
  const solid = D.axes.filter((a) => !a.weak);
  const noisy = D.axes.filter((a) => a.weak);

  out.push(`# ${name} — eidoscope report\n`);
  out.push(`**${n} documents**${span ? ` · ${span}` : ""} · ${D.k} regions · ${solid.length} solid axes${noisy.length ? ` (+${noisy.length} too noisy to trust)` : ""}\n`);

  // What it's about — regions by size, each with its most-central (highest-hub) member
  out.push(`## What it's about\n`);
  const bySize = D.clusters.slice().sort((a, b) => b.n - a.n);
  for (const c of bySize) {
    const members = D.ids.map((_, i) => i).filter((i) => D.cluster[i] === c.c);
    const top = members.sort((a, b) => (hub[b] || 0) - (hub[a] || 0))[0];
    out.push(`- **${c.label}** (${c.n})${top != null ? ` — e.g. *${D.titles[top]}*` : ""}`);
  }

  // How it varies — LEAD with the axes that held up under the fidelity check; the ones the cards
  // don't track get quarantined below, not listed as equals. The tool knows which are noise — say so.
  out.push(`\n## How it varies\n`);
  out.push(solid.length
    ? `The dimensions the corpus actually spreads along — these **${solid.length}** held up under the fidelity check (the cards track them):\n`
    : `⚠ **None** of the discovered axes held up under the fidelity check — treat the map's axes as noise.\n`);
  for (const a of solid) out.push(`- **${a.name}** — ${a.low} ↔ ${a.high}`);
  if (solid.length >= 2) {
    const rg = scoreRedundancy(Object.fromEntries(solid.map((a) => [a.key, D.scores[a.key]])));
    out.push(`\n_Axis distinctness (solid axes): mean |r| ${rg.meanAbsR.toFixed(2)} ${rg.pass ? "— genuinely distinct lenses." : `— ⚠ ${rg.strong} pairs overlap; treat some as one._`}`);
  }
  if (noisy.length) {
    out.push(`\n**${noisy.length} discovered axes did _not_ hold up** — the cards don't track them, so don't read meaning into these:\n`);
    for (const a of noisy) out.push(`- ~~${a.name}~~ — ${a.low} ↔ ${a.high}  _(noisy)_`);
  }

  // Read next — highest-influence documents, filtered to unread when read-state is known
  const known = (D.read || []).some((r) => r !== undefined);
  const readN = (D.read || []).filter((r) => r === true).length;
  out.push(`\n## Read next\n`);
  out.push(known
    ? `You've opened **${readN} of ${n}** (${Math.round((100 * readN) / n)}%). The most influential of the **${n - readN}** you haven't:\n`
    : `The most connected documents (structural influence):\n`);
  const pool = D.ids.map((_, i) => i).filter((i) => !known || D.read?.[i] !== true);
  pool.sort((a, b) => (hub[b] || 0) - (hub[a] || 0)).slice(0, 10).forEach((i, r) => out.push(`${r + 1}. ${link(i)} — *${regionOf(i)}*`));

  // Frontier — the canon you cite but don't own
  if (D.ghosts && D.ghosts.length) {
    out.push(`\n## Your frontier — ${D.ghosts.length} papers you cite but don't own\nThe foundations just outside your library, by how many of your documents cite each:\n`);
    D.ghosts.slice().sort((a, b) => b.n - a.n).slice(0, 12).forEach((g, r) =>
      out.push(`${r + 1}. [${g.title}](${g.url}) — cited by **${g.n}** of your docs`));
  }

  out.push(`\n---\n_Generated by [eidoscope](https://github.com/deepfates/eidoscope). Open \`eidoscope.html\` for the interactive map._`);
  return out.join("\n") + "\n";
}
